### Hello world
GET http://localhost:9010/auth/hello
Content-Type: application/json

### Login with email and password
POST http://localhost:9010/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### Firebase Login with token
POST http://localhost:9010/auth/firebase
Content-Type: application/json

{
  "token": "your-firebase-id-token"
}