### Hello world
GET http://localhost:9010/auth/hello
Content-Type: application/json

### Login with email and password
POST http://localhost:9010/auth/login
Content-Type: application/json

{
  "email": "user6@example.com",
  "password": "password123"
}

### Signup with email and password
POST http://localhost:9010/auth/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}


GET http://localhost:9010/auth/get_user_id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyNkBleGFtcGxlLmNvbSIsImV4cCI6MTc0MDU5MDUwMn0.VCf0VLT5iqs3dkputt5ID6Dj38C4uBYfYujLxEZv3og
Content-Type: application/json

### Firebase Login with token
POST http://localhost:9010/auth/firebase
Content-Type: application/json

{
  "token": "your-firebase-id-token"
}